// flow-typed signature: 12376f6da8de746932e11ab0c4a6369b
// flow-typed version: <<STUB>>/bfj_v5.2.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bfj'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bfj' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bfj/src/error' {
  declare module.exports: any;
}

declare module 'bfj/src/eventify' {
  declare module.exports: any;
}

declare module 'bfj/src/events' {
  declare module.exports: any;
}

declare module 'bfj/src/index' {
  declare module.exports: any;
}

declare module 'bfj/src/jsonstream' {
  declare module.exports: any;
}

declare module 'bfj/src/memory' {
  declare module.exports: any;
}

declare module 'bfj/src/parse' {
  declare module.exports: any;
}

declare module 'bfj/src/promise' {
  declare module.exports: any;
}

declare module 'bfj/src/read' {
  declare module.exports: any;
}

declare module 'bfj/src/streamify' {
  declare module.exports: any;
}

declare module 'bfj/src/stringify' {
  declare module.exports: any;
}

declare module 'bfj/src/unpipe' {
  declare module.exports: any;
}

declare module 'bfj/src/walk' {
  declare module.exports: any;
}

declare module 'bfj/src/write' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bfj/src/error.js' {
  declare module.exports: $Exports<'bfj/src/error'>;
}
declare module 'bfj/src/eventify.js' {
  declare module.exports: $Exports<'bfj/src/eventify'>;
}
declare module 'bfj/src/events.js' {
  declare module.exports: $Exports<'bfj/src/events'>;
}
declare module 'bfj/src/index.js' {
  declare module.exports: $Exports<'bfj/src/index'>;
}
declare module 'bfj/src/jsonstream.js' {
  declare module.exports: $Exports<'bfj/src/jsonstream'>;
}
declare module 'bfj/src/memory.js' {
  declare module.exports: $Exports<'bfj/src/memory'>;
}
declare module 'bfj/src/parse.js' {
  declare module.exports: $Exports<'bfj/src/parse'>;
}
declare module 'bfj/src/promise.js' {
  declare module.exports: $Exports<'bfj/src/promise'>;
}
declare module 'bfj/src/read.js' {
  declare module.exports: $Exports<'bfj/src/read'>;
}
declare module 'bfj/src/streamify.js' {
  declare module.exports: $Exports<'bfj/src/streamify'>;
}
declare module 'bfj/src/stringify.js' {
  declare module.exports: $Exports<'bfj/src/stringify'>;
}
declare module 'bfj/src/unpipe.js' {
  declare module.exports: $Exports<'bfj/src/unpipe'>;
}
declare module 'bfj/src/walk.js' {
  declare module.exports: $Exports<'bfj/src/walk'>;
}
declare module 'bfj/src/write.js' {
  declare module.exports: $Exports<'bfj/src/write'>;
}
