// flow-typed signature: 9c0bb5d5e633955319a7eb4d986cbeb5
// flow-typed version: <<STUB>>/case-sensitive-paths-webpack-plugin_v2.1.2/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'case-sensitive-paths-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'case-sensitive-paths-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'case-sensitive-paths-webpack-plugin/index' {
  declare module.exports: $Exports<'case-sensitive-paths-webpack-plugin'>;
}
declare module 'case-sensitive-paths-webpack-plugin/index.js' {
  declare module.exports: $Exports<'case-sensitive-paths-webpack-plugin'>;
}
