// flow-typed signature: 3c61bdbc905e121a9bfe0d9904069e58
// flow-typed version: <<STUB>>/chai-jsx_v^1.0.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chai-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'chai-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chai-jsx/chai-jsx' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chai-jsx/chai-jsx.js' {
  declare module.exports: $Exports<'chai-jsx/chai-jsx'>;
}
