// flow-typed signature: 19c0acd5a960f0029ff25e0661040bcb
// flow-typed version: <<STUB>>/eslint-plugin-jsx-a11y_v6.0.3/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-jsx-a11y'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-jsx-a11y' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-jsx-a11y/__mocks__/genInteractives' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/__mocks__/IdentifierMock' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/__mocks__/JSXAttributeMock' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/__mocks__/JSXElementMock' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/__mocks__/JSXExpressionContainerMock' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/accessible-emoji' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/alt-text' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/anchor-has-content' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/anchor-is-valid' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/aria-activedescendant-has-tabindex' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/aria-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/aria-proptypes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/aria-role' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/aria-unsupported-elements' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/click-events-have-key-events' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/heading-has-content' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/html-has-lang' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/iframe-has-title' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/img-redundant-alt' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/interactive-supports-focus' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/label-has-for' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/lang' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/media-has-caption' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/mouse-events-have-key-events' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/no-access-key' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/no-autofocus' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/no-distracting-elements' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/no-interactive-element-to-noninteractive-role' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/no-noninteractive-element-interactions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/no-noninteractive-element-to-interactive-role' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/no-noninteractive-tabindex' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/no-onchange' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/no-redundant-roles' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/no-static-element-interactions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/role-has-required-aria-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/role-supports-aria-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/scope' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/tabindex-no-positive' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/attributesComparator' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/getImplicitRole' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/getSuggestion' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/getTabIndex' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/hasAccessibleChild' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/a' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/area' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/article' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/aside' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/body' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/button' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/datalist' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/details' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/dialog' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/dl' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/form' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h1' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h2' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h3' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h4' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h5' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h6' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/hr' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/img' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/input' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/li' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/link' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/menu' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/menuitem' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/meter' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/nav' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/ol' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/option' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/output' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/progress' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/section' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/select' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/tbody' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/textarea' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/tfoot' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/thead' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/ul' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/isAbstractRole' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/isHiddenFromScreenReader' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/isInteractiveElement' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/isInteractiveRole' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/isNonInteractiveElement' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/isNonInteractiveRole' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/isPresentationRole' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/schemas' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/scripts/addRuleToIndex' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/scripts/boilerplate/doc' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/scripts/boilerplate/rule' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/scripts/boilerplate/test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/scripts/create-rule' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-jsx-a11y/__mocks__/genInteractives.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/__mocks__/genInteractives'>;
}
declare module 'eslint-plugin-jsx-a11y/__mocks__/IdentifierMock.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/__mocks__/IdentifierMock'>;
}
declare module 'eslint-plugin-jsx-a11y/__mocks__/JSXAttributeMock.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/__mocks__/JSXAttributeMock'>;
}
declare module 'eslint-plugin-jsx-a11y/__mocks__/JSXElementMock.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/__mocks__/JSXElementMock'>;
}
declare module 'eslint-plugin-jsx-a11y/__mocks__/JSXExpressionContainerMock.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/__mocks__/JSXExpressionContainerMock'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/index'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/accessible-emoji.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/accessible-emoji'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/alt-text.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/alt-text'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/anchor-has-content.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/anchor-has-content'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/anchor-is-valid.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/anchor-is-valid'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/aria-activedescendant-has-tabindex.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/aria-activedescendant-has-tabindex'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/aria-props.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/aria-props'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/aria-proptypes.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/aria-proptypes'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/aria-role.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/aria-role'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/aria-unsupported-elements.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/aria-unsupported-elements'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/click-events-have-key-events.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/click-events-have-key-events'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/heading-has-content.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/heading-has-content'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/html-has-lang.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/html-has-lang'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/iframe-has-title.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/iframe-has-title'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/img-redundant-alt.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/img-redundant-alt'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/interactive-supports-focus.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/interactive-supports-focus'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/label-has-for.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/label-has-for'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/lang.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/lang'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/media-has-caption.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/media-has-caption'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/mouse-events-have-key-events.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/mouse-events-have-key-events'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/no-access-key.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/no-access-key'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/no-autofocus.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/no-autofocus'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/no-distracting-elements.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/no-distracting-elements'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/no-interactive-element-to-noninteractive-role.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/no-interactive-element-to-noninteractive-role'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/no-noninteractive-element-interactions.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/no-noninteractive-element-interactions'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/no-noninteractive-element-to-interactive-role.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/no-noninteractive-element-to-interactive-role'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/no-noninteractive-tabindex.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/no-noninteractive-tabindex'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/no-onchange.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/no-onchange'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/no-redundant-roles.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/no-redundant-roles'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/no-static-element-interactions.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/no-static-element-interactions'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/role-has-required-aria-props.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/role-has-required-aria-props'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/role-supports-aria-props.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/role-supports-aria-props'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/scope.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/scope'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/tabindex-no-positive.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/tabindex-no-positive'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/attributesComparator.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/attributesComparator'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/getImplicitRole.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/getImplicitRole'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/getSuggestion.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/getSuggestion'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/getTabIndex.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/getTabIndex'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/hasAccessibleChild.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/hasAccessibleChild'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/a.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/a'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/area.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/area'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/article.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/article'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/aside.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/aside'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/body.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/body'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/button.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/button'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/datalist.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/datalist'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/details.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/details'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/dialog.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/dialog'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/dl.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/dl'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/form.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/form'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h1.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h1'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h2.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h2'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h3.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h3'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h4.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h4'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h5.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h5'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h6.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h6'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/hr.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/hr'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/img.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/img'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/index'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/input.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/input'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/li.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/li'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/link.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/link'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/menu.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/menu'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/menuitem.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/menuitem'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/meter.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/meter'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/nav.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/nav'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/ol.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/ol'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/option.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/option'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/output.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/output'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/progress.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/progress'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/section.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/section'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/select.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/select'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/tbody.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/tbody'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/textarea.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/textarea'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/tfoot.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/tfoot'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/thead.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/thead'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/ul.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/ul'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/isAbstractRole.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/isAbstractRole'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/isHiddenFromScreenReader.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/isHiddenFromScreenReader'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/isInteractiveElement.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/isInteractiveElement'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/isInteractiveRole.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/isInteractiveRole'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/isNonInteractiveElement.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/isNonInteractiveElement'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/isNonInteractiveRole.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/isNonInteractiveRole'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/isPresentationRole.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/isPresentationRole'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/schemas.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/schemas'>;
}
declare module 'eslint-plugin-jsx-a11y/scripts/addRuleToIndex.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/scripts/addRuleToIndex'>;
}
declare module 'eslint-plugin-jsx-a11y/scripts/boilerplate/doc.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/scripts/boilerplate/doc'>;
}
declare module 'eslint-plugin-jsx-a11y/scripts/boilerplate/rule.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/scripts/boilerplate/rule'>;
}
declare module 'eslint-plugin-jsx-a11y/scripts/boilerplate/test.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/scripts/boilerplate/test'>;
}
declare module 'eslint-plugin-jsx-a11y/scripts/create-rule.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/scripts/create-rule'>;
}
