// flow-typed signature: 3b2425c6154b7d7f0d352f52eb47d09f
// flow-typed version: <<STUB>>/normalize.css_v^5.0.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
