// flow-typed signature: d7725bcaf12a3b6f864153db7c6ef07c
// flow-typed version: <<STUB>>/optimize-css-assets-webpack-plugin_v^4.0.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'optimize-css-assets-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'optimize-css-assets-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'optimize-css-assets-webpack-plugin/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'optimize-css-assets-webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'optimize-css-assets-webpack-plugin/src/index'>;
}
