// flow-typed signature: f80ffc78652c76bd2a76454c37bc508c
// flow-typed version: <<STUB>>/postcss-units_v^1.1.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-units'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-units' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-units/index' {
  declare module.exports: $Exports<'postcss-units'>;
}
declare module 'postcss-units/index.js' {
  declare module.exports: $Exports<'postcss-units'>;
}
