// flow-typed signature: 6dfb84e592030164684ec5175970de93
// flow-typed version: <<STUB>>/resolve_v1.6.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'resolve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'resolve' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'resolve/lib/async' {
  declare module.exports: any;
}

declare module 'resolve/lib/caller' {
  declare module.exports: any;
}

declare module 'resolve/lib/core' {
  declare module.exports: any;
}

declare module 'resolve/lib/node-modules-paths' {
  declare module.exports: any;
}

declare module 'resolve/lib/sync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'resolve/index' {
  declare module.exports: $Exports<'resolve'>;
}
declare module 'resolve/index.js' {
  declare module.exports: $Exports<'resolve'>;
}
declare module 'resolve/lib/async.js' {
  declare module.exports: $Exports<'resolve/lib/async'>;
}
declare module 'resolve/lib/caller.js' {
  declare module.exports: $Exports<'resolve/lib/caller'>;
}
declare module 'resolve/lib/core.js' {
  declare module.exports: $Exports<'resolve/lib/core'>;
}
declare module 'resolve/lib/node-modules-paths.js' {
  declare module.exports: $Exports<'resolve/lib/node-modules-paths'>;
}
declare module 'resolve/lib/sync.js' {
  declare module.exports: $Exports<'resolve/lib/sync'>;
}
